server:
  port: 8001

spring:
  application:
    name: cloud-secKill-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver                 # dif
    url: "jdbc:mysql://localhost:3306/fabflix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: root
    password: Yqr199733dlj*
  redis:
    host: localhost
    port: 6379

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spike.cloud.entities        # dif

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # eureka cluster

  instance:
    instance-id: secKill-consumer${server.port}
    prefer-ip-address: true
